### ISSUE TITLE
Visual issues with the library (PBP 0.2 BETA)

### ISSUE THREAD

**Issue by Q99kek** [ProjectBlackPearl/pbpl#20]
1. Titles and descriptions should have a maximum character limit to them. Right now you could post a whole 15 page essay and it just doesn't look good visually.
2. There should be a search bar implemented for the library since it can get pretty difficult to find what you're looking for when you have a lot of games there and have to scroll to narnia to find something. There should also be alternative ways to view your games so it looks cleaner. (Example: Epic Games library, Steam library, generally just having the games only shown as small icons if the user prefers it that way)

**Comment by zun1uwu** [comment]
Regarding the third concern, I will try to make it possible with a custom theme system :3

**Comment by Brisolo32** [comment]
Description limit has been added on [pbpl/20-library-additions](https://github.com/ProjectBlackPearl/pbpl/tree/20-library-additions)

**Comment by infinity-plus** [comment]
@Q99kek , 
Both changes were merged by #21 .
Thank you for your feedback.
